apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: osdc-monitoring
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
  endpoints:
    - port: metrics
      interval: 30s
      metricRelabelings:
        - action: labeldrop
          regex: UUID
        - action: labeldrop
          regex: modelName
        - action: labeldrop
          regex: DCGM_FI_DRIVER_VERSION
        - action: labeldrop
          regex: pci_bus_id
