apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-compactor
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: osdc-monitoring
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: node-compactor
  endpoints:
    - port: metrics
      interval: 60s
