apiVersion: v1
kind: ServiceAccount
metadata:
  name: pypi-cache
  namespace: pypi-cache
  labels:
    osdc.io/module: pypi-cache
    app.kubernetes.io/name: pypi-cache
    app.kubernetes.io/component: package-cache
