apiVersion: v1
kind: ServiceAccount
metadata:
  name: pypi-wants-collector
  namespace: pypi-cache
  labels:
    app.kubernetes.io/name: pypi-wants-collector
    app.kubernetes.io/component: wants-collector
