apiVersion: v1
kind: ServiceAccount
metadata:
  name: pypi-wheel-syncer
  namespace: pypi-cache
  labels:
    osdc.io/module: pypi-cache
    app.kubernetes.io/name: pypi-wheel-syncer
    app.kubernetes.io/component: wheel-syncer
