apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: nodeclass-$(NODETYPE)
spec:
  amiFamily: AL2
  subnetSelectorTerms: $(KARPENTERSUBNETIDS)
  securityGroupSelectorTerms: $(KARPENTERSGIDS)
  role: "$(KARPENTERNODEROLE)"
  detailedMonitoring: true
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 500Gi
        volumeType: gp3
        deleteOnTermination: true
