apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: nodeclass-$(NODETYPE)
spec:
  amiFamily: AL2
  subnetSelectorTerms: $(KARPENTERSUBNETIDS)
  securityGroupSelectorTerms: $(KARPENTERSGIDS)
  role: "$(KARPENTERNODEROLE)"
  detailedMonitoring: true
