---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-role-binding
  namespace: actions-runner-system
subjects:
- kind: ServiceAccount
  name: runner-service-account
  namespace: actions-runner-system
roleRef:
  kind: Role
  name: runner-role
  apiGroup: rbac.authorization.k8s.io
