githubConfigUrl: "$(RUNNERSCOPE)"

githubConfigSecret: "gha-arc-secret"

maxRunners: $(MAXRUNNERS)

minRunners: $(MINRUNNERS)

runnerGroup: "$(RUNNERGROUP)"

runnerScaleSetName: "$(RUNNERLABEL)"

containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "gp2"
    resources:
      requests:
        storage: 1Gi
  kubernetesModeServiceAccount:
    annotations:

listenerTemplate:
  spec:
    containers:
      - name: listener
        securityContext:
          runAsUser: 1000
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: Exists
        effect: NoSchedule

template:
  spec:
    tolerations:
      - key: "arcRunnerNodeType-$(NODETYPE)"
        operator: Exists
        effect: NoSchedule
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      env:
      - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
        value: "false"
