apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: $NAME
spec:
  template:
    spec:
      ephemeral: true

      organization: "pytorch"

      labels:
        - $NAME

      env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              runner-deployment-name: $NAME

      imagePullPolicy: Always
      resources:
        limits:
          cpu: "4.0"
          memory: "8Gi"
        requests:
          cpu: "4.0"
          memory: "8Gi"

      dockerVolumeMounts:
      - mountPath: /var/lib/docker
        name: docker
        subPathExpr: $(POD_NAME)-docker

      volumeMounts:
      - mountPath: /runner/_work
        name: work
        subPathExpr: $(POD_NAME)-work
      - mountPath: /tmp
        name: tmp
        subPathExpr: $(POD_NAME)-tmp

      dockerEnv:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name

      volumes:
      - name: docker
        emptyDir:
          sizeLimit: 20Gi
      - name: work
        emptyDir:
          sizeLimit: 150Gi
      - name: tmp
        emptyDir:
          sizeLimit: 50Gi
