# Service for the central git cache pod.
# DaemonSet pods connect to this service to rsync the cache.
apiVersion: v1
kind: Service
metadata:
  name: git-cache-central
  namespace: kube-system
  labels:
    app: git-cache-central
spec:
  type: ClusterIP
  ports:
    - name: rsync
      port: 873
      targetPort: 873
      protocol: TCP
  selector:
    app: git-cache-central
