apiVersion: v1
kind: Service
metadata:
  name: git-cache-central-metrics
  namespace: kube-system
  labels:
    app: git-cache-central
    app.kubernetes.io/name: git-cache-central
    app.kubernetes.io/component: git-cache
spec:
  selector:
    app: git-cache-central
  ports:
    - name: metrics
      port: 9101
      targetPort: metrics
      protocol: TCP
