# Auto-generated by OSDC integration test orchestrator.
# Do not edit manually — regenerated on each test run.
name: "OSDC Integration Test"

on:
  pull_request:

concurrency:
  group: osdc-integration-test-{{CLUSTER_ID}}
  cancel-in-progress: true

jobs:
  # ── CPU Runner Tests ──────────────────────────────────────────────────
  test-cpu-x86-avx512:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify CPU architecture
        run: |
          echo "=== CPU Info ==="
          lscpu
          echo ""
          echo "=== Checking x86_64 ==="
          ARCH=$(uname -m)
          if [ "$ARCH" != "x86_64" ]; then
            echo "FAIL: Expected x86_64, got $ARCH"
            exit 1
          fi
          echo "PASS: Architecture is $ARCH"
      - name: Verify AVX-512 support
        run: |
          if grep -q avx512 /proc/cpuinfo; then
            echo "PASS: AVX-512 flags found"
          else
            echo "FAIL: AVX-512 flags not found in /proc/cpuinfo"
            exit 1
          fi
      - name: Verify CPU count
        run: |
          EXPECTED=8
          ACTUAL=$(nproc)
          echo "CPUs: $ACTUAL (expected: $EXPECTED)"
          if [ "$ACTUAL" -ne "$EXPECTED" ]; then
            echo "FAIL: Expected $EXPECTED CPUs, got $ACTUAL"
            exit 1
          fi
          echo "PASS: CPU count matches"
      - name: Verify memory
        run: |
          EXPECTED_GI=32
          if [ -f /sys/fs/cgroup/memory.max ] && [ "$(cat /sys/fs/cgroup/memory.max)" != "max" ]; then
            BYTES=$(cat /sys/fs/cgroup/memory.max)
          elif [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ]; then
            BYTES=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
          else
            BYTES=$(awk '/MemTotal/ {print $2 * 1024}' /proc/meminfo)
          fi
          ACTUAL_GI=$((BYTES / 1073741824))
          echo "Memory: ${ACTUAL_GI}Gi (expected: ${EXPECTED_GI}Gi)"
          MIN_GI=$((EXPECTED_GI * 90 / 100))
          if [ "$ACTUAL_GI" -lt "$MIN_GI" ]; then
            echo "FAIL: Memory below expected (${ACTUAL_GI}Gi < ${MIN_GI}Gi minimum)"
            exit 1
          fi
          echo "PASS: Memory within expected range"
      - name: Verify TORCH_CI_MAX_MEMORY
        run: |
          echo "=== TORCH_CI_MAX_MEMORY ==="
          EXPECTED=34359738368
          ACTUAL="${TORCH_CI_MAX_MEMORY:-}"
          echo "TORCH_CI_MAX_MEMORY=$ACTUAL (expected: $EXPECTED)"
          if [ -z "$ACTUAL" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY is not set"
            exit 1
          fi
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY mismatch"
            exit 1
          fi
          echo "PASS: TORCH_CI_MAX_MEMORY is correct"
      - name: Verify environment
        run: |
          echo "=== Environment ==="
          echo "CHECKOUT_GIT_CACHE_DIR=${CHECKOUT_GIT_CACHE_DIR:-NOT SET}"
          echo "GIT_CONFIG_SYSTEM=${GIT_CONFIG_SYSTEM:-NOT SET}"
          echo "ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER=${ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER:-NOT SET}"
          if [ -z "${CHECKOUT_GIT_CACHE_DIR:-}" ]; then
            echo "FAIL: CHECKOUT_GIT_CACHE_DIR not set"
            exit 1
          fi
          echo "PASS: Required env vars present"

  test-cpu-x86-amx:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify CPU architecture
        run: |
          echo "=== CPU Info ==="
          lscpu
          ARCH=$(uname -m)
          if [ "$ARCH" != "x86_64" ]; then
            echo "FAIL: Expected x86_64, got $ARCH"
            exit 1
          fi
          echo "PASS: Architecture is $ARCH"
      - name: Verify AMX support
        run: |
          if grep -q amx /proc/cpuinfo; then
            echo "PASS: AMX flags found"
          else
            echo "WARN: AMX flags not found (may not be exposed in container)"
          fi
      - name: Verify CPU count
        run: |
          EXPECTED=8
          ACTUAL=$(nproc)
          echo "CPUs: $ACTUAL (expected: $EXPECTED)"
          if [ "$ACTUAL" -ne "$EXPECTED" ]; then
            echo "FAIL: Expected $EXPECTED CPUs, got $ACTUAL"
            exit 1
          fi
          echo "PASS: CPU count matches"
      - name: Verify memory
        run: |
          EXPECTED_GI=32
          if [ -f /sys/fs/cgroup/memory.max ] && [ "$(cat /sys/fs/cgroup/memory.max)" != "max" ]; then
            BYTES=$(cat /sys/fs/cgroup/memory.max)
          elif [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ]; then
            BYTES=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
          else
            BYTES=$(awk '/MemTotal/ {print $2 * 1024}' /proc/meminfo)
          fi
          ACTUAL_GI=$((BYTES / 1073741824))
          echo "Memory: ${ACTUAL_GI}Gi (expected: ${EXPECTED_GI}Gi)"
          MIN_GI=$((EXPECTED_GI * 90 / 100))
          if [ "$ACTUAL_GI" -lt "$MIN_GI" ]; then
            echo "FAIL: Memory below expected (${ACTUAL_GI}Gi < ${MIN_GI}Gi minimum)"
            exit 1
          fi
          echo "PASS: Memory within expected range"
      - name: Verify TORCH_CI_MAX_MEMORY
        run: |
          echo "=== TORCH_CI_MAX_MEMORY ==="
          EXPECTED=34359738368
          ACTUAL="${TORCH_CI_MAX_MEMORY:-}"
          echo "TORCH_CI_MAX_MEMORY=$ACTUAL (expected: $EXPECTED)"
          if [ -z "$ACTUAL" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY is not set"
            exit 1
          fi
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY mismatch"
            exit 1
          fi
          echo "PASS: TORCH_CI_MAX_MEMORY is correct"

  test-cpu-arm64:
    runs-on: {{PREFIX}}l-arm64g3-16-62
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify CPU architecture
        run: |
          echo "=== CPU Info ==="
          lscpu
          ARCH=$(uname -m)
          if [ "$ARCH" != "aarch64" ]; then
            echo "FAIL: Expected aarch64, got $ARCH"
            exit 1
          fi
          echo "PASS: Architecture is $ARCH"
      - name: Verify CPU count
        run: |
          EXPECTED=16
          ACTUAL=$(nproc)
          echo "CPUs: $ACTUAL (expected: $EXPECTED)"
          if [ "$ACTUAL" -ne "$EXPECTED" ]; then
            echo "FAIL: Expected $EXPECTED CPUs, got $ACTUAL"
            exit 1
          fi
          echo "PASS: CPU count matches"
      - name: Verify memory
        run: |
          EXPECTED_GI=62
          if [ -f /sys/fs/cgroup/memory.max ] && [ "$(cat /sys/fs/cgroup/memory.max)" != "max" ]; then
            BYTES=$(cat /sys/fs/cgroup/memory.max)
          elif [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ]; then
            BYTES=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
          else
            BYTES=$(awk '/MemTotal/ {print $2 * 1024}' /proc/meminfo)
          fi
          ACTUAL_GI=$((BYTES / 1073741824))
          echo "Memory: ${ACTUAL_GI}Gi (expected: ${EXPECTED_GI}Gi)"
          MIN_GI=$((EXPECTED_GI * 90 / 100))
          if [ "$ACTUAL_GI" -lt "$MIN_GI" ]; then
            echo "FAIL: Memory below expected (${ACTUAL_GI}Gi < ${MIN_GI}Gi minimum)"
            exit 1
          fi
          echo "PASS: Memory within expected range"
      - name: Verify TORCH_CI_MAX_MEMORY
        run: |
          echo "=== TORCH_CI_MAX_MEMORY ==="
          EXPECTED=66571993088
          ACTUAL="${TORCH_CI_MAX_MEMORY:-}"
          echo "TORCH_CI_MAX_MEMORY=$ACTUAL (expected: $EXPECTED)"
          if [ -z "$ACTUAL" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY is not set"
            exit 1
          fi
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY mismatch"
            exit 1
          fi
          echo "PASS: TORCH_CI_MAX_MEMORY is correct"
      - name: Verify environment
        run: |
          echo "CHECKOUT_GIT_CACHE_DIR=${CHECKOUT_GIT_CACHE_DIR:-NOT SET}"
          if [ -z "${CHECKOUT_GIT_CACHE_DIR:-}" ]; then
            echo "FAIL: CHECKOUT_GIT_CACHE_DIR not set"
            exit 1
          fi
          echo "PASS: Required env vars present"

  # ── Pip Install Test ─────────────────────────────────────────────────
  test-pip-install:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: python:3.12-slim
    steps:
      - name: Verify pip install
        run: |
          echo "=== Pip Install Test ==="
          pip install --no-cache-dir six packaging typing-extensions
          python -c "from importlib.metadata import version; print(f'six=={version(\"six\")}')"
          python -c "from importlib.metadata import version; print(f'packaging=={version(\"packaging\")}')"
          python -c "from importlib.metadata import version; print(f'typing-extensions=={version(\"typing-extensions\")}')"
          echo "PASS: pip install and import succeeded"

  # ── UV Install Test ────────────────────────────────────────────────────
  # uv has two distinct resolution paths (pip-interface and project-interface)
  # that resolve indexes differently. Test both to verify UV_DEFAULT_INDEX works.
  test-uv-pip-install:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: python:3.12-slim
    steps:
      - name: Verify uv pip install
        run: |
          echo "=== UV pip install Test ==="
          pip install --no-cache-dir uv
          uv pip install --system --no-cache six packaging typing-extensions
          python -c "from importlib.metadata import version; print(f'six=={version(\"six\")}')"
          python -c "from importlib.metadata import version; print(f'packaging=={version(\"packaging\")}')"
          python -c "from importlib.metadata import version; print(f'typing-extensions=={version(\"typing-extensions\")}')"
          echo "PASS: uv pip install succeeded"

  test-uv-pip-compile-sync:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: python:3.12-slim
    steps:
      - name: Verify uv pip compile and sync
        run: |
          echo "=== UV pip compile + sync Test ==="
          pip install --no-cache-dir uv
          printf 'six\npackaging\ntyping-extensions\n' > requirements.in
          uv pip compile --no-cache --no-config requirements.in -o requirements.txt
          uv pip sync --system --no-cache --no-config requirements.txt
          python -c "from importlib.metadata import version; print(f'six=={version(\"six\")}')"
          python -c "from importlib.metadata import version; print(f'packaging=={version(\"packaging\")}')"
          python -c "from importlib.metadata import version; print(f'typing-extensions=={version(\"typing-extensions\")}')"
          echo "PASS: uv pip compile + sync succeeded"

  test-uv-project:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: python:3.12-slim
    steps:
      - name: Verify uv add and run
        run: |
          echo "=== UV project interface Test ==="
          pip install --no-cache-dir uv
          uv init --no-cache test-project && cd test-project
          uv add --no-cache six packaging typing-extensions
          uv run --no-cache python -c "from importlib.metadata import version; print(f'six=={version(\"six\")}')"
          uv run --no-cache python -c "from importlib.metadata import version; print(f'packaging=={version(\"packaging\")}')"
          uv run --no-cache python -c "from importlib.metadata import version; print(f'typing-extensions=={version(\"typing-extensions\")}')"
          echo "PASS: uv project interface succeeded"

  # ── Git Cache Test ────────────────────────────────────────────────────
  test-git-cache:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify cache mount
        run: |
          echo "=== Git Cache ==="
          echo "CHECKOUT_GIT_CACHE_DIR=${CHECKOUT_GIT_CACHE_DIR:-NOT SET}"
          if [ ! -d "${CHECKOUT_GIT_CACHE_DIR:-/nonexistent}" ]; then
            echo "FAIL: Git cache directory not mounted"
            exit 1
          fi
          echo "PASS: Git cache directory exists at $CHECKOUT_GIT_CACHE_DIR"
          echo ""
          echo "=== Cache contents ==="
          ls -la "$CHECKOUT_GIT_CACHE_DIR/" || true
      - name: Verify pytorch cache
        run: |
          CACHE_DIR="$CHECKOUT_GIT_CACHE_DIR/pytorch"
          if [ ! -d "$CACHE_DIR/.git/objects" ]; then
            echo "FAIL: pytorch/.git/objects not found"
            echo "Cache dir contents:"
            ls -la "$CHECKOUT_GIT_CACHE_DIR/" 2>/dev/null || echo "(empty)"
            exit 1
          fi
          OBJ_COUNT=$(find "$CACHE_DIR/.git/objects" -type f 2>/dev/null | head -100 | wc -l)
          echo "PASS: pytorch/pytorch cache has objects (sampled $OBJ_COUNT files)"
      - name: Verify test-infra cache
        run: |
          CACHE_DIR="$CHECKOUT_GIT_CACHE_DIR/test-infra.git"
          if [ ! -d "$CACHE_DIR/objects" ]; then
            echo "FAIL: test-infra.git/objects not found"
            exit 1
          fi
          echo "PASS: pytorch/test-infra cache present"
      - name: Test fast checkout with cache
        uses: actions/checkout@v4
        with:
          repository: pytorch/pytorch
          ref: main
          path: pytorch-checkout
          fetch-depth: 1
      - name: Verify checkout
        run: |
          if [ ! -f "pytorch-checkout/setup.py" ]; then
            echo "FAIL: Checkout doesn't look like pytorch/pytorch"
            exit 1
          fi
          echo "PASS: pytorch/pytorch checkout verified"

  # ── GPU Runner Tests ──────────────────────────────────────────────────
  test-gpu-t4:
    runs-on: {{PREFIX}}l-x86iavx512-29-115-t4
    container:
      image: nvidia/cuda:12.6.3-base-ubuntu22.04
    steps:
      - name: Verify GPU
        run: |
          echo "=== nvidia-smi ==="
          nvidia-smi
          echo ""
          GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
          if [ "$GPU_COUNT" -lt 1 ]; then
            echo "FAIL: Expected at least 1 GPU, found $GPU_COUNT"
            exit 1
          fi
          echo "PASS: Found $GPU_COUNT GPU(s)"
      - name: Verify GPU model
        run: |
          GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
          echo "GPU: $GPU_NAME"
          if echo "$GPU_NAME" | grep -qi "t4"; then
            echo "PASS: GPU is T4"
          else
            echo "WARN: Expected T4, got $GPU_NAME"
          fi
      - name: Verify CUDA
        run: |
          echo "=== CUDA Version ==="
          nvcc --version 2>/dev/null || echo "nvcc not in PATH (base image only)"
          nvidia-smi --query-gpu=driver_version --format=csv,noheader
          echo "PASS: GPU driver responsive"
      - name: Verify TORCH_CI_MAX_MEMORY
        run: |
          echo "=== TORCH_CI_MAX_MEMORY ==="
          EXPECTED=123480309760
          ACTUAL="${TORCH_CI_MAX_MEMORY:-}"
          echo "TORCH_CI_MAX_MEMORY=$ACTUAL (expected: $EXPECTED)"
          if [ -z "$ACTUAL" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY is not set"
            exit 1
          fi
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY mismatch"
            exit 1
          fi
          echo "PASS: TORCH_CI_MAX_MEMORY is correct"

  test-gpu-t4-multi:
    runs-on: {{PREFIX}}l-x86iavx512-45-172-t4-4
    container:
      image: nvidia/cuda:12.6.3-base-ubuntu22.04
    steps:
      - name: Verify multi-GPU
        run: |
          echo "=== nvidia-smi ==="
          nvidia-smi
          echo ""
          GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
          if [ "$GPU_COUNT" -ne 4 ]; then
            echo "FAIL: Expected 4 GPUs, found $GPU_COUNT"
            exit 1
          fi
          echo "PASS: Found $GPU_COUNT GPUs"
      - name: Verify GPU topology
        run: |
          echo "=== GPU Topology ==="
          nvidia-smi topo -m
      - name: Verify TORCH_CI_MAX_MEMORY
        run: |
          echo "=== TORCH_CI_MAX_MEMORY ==="
          EXPECTED=184683593728
          ACTUAL="${TORCH_CI_MAX_MEMORY:-}"
          echo "TORCH_CI_MAX_MEMORY=$ACTUAL (expected: $EXPECTED)"
          if [ -z "$ACTUAL" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY is not set"
            exit 1
          fi
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY mismatch"
            exit 1
          fi
          echo "PASS: TORCH_CI_MAX_MEMORY is correct"

  # BEGIN_B200
  test-gpu-b200-2:
    runs-on: {{PREFIX}}a.linux.b200.2
    container:
      image: nvidia/cuda:12.6.3-base-ubuntu22.04
    steps:
      - name: Verify B200 multi-GPU
        run: |
          echo "=== nvidia-smi ==="
          nvidia-smi
          echo ""
          GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
          if [ "$GPU_COUNT" -ne 2 ]; then
            echo "FAIL: Expected 2 GPUs, found $GPU_COUNT"
            exit 1
          fi
          echo "PASS: Found $GPU_COUNT B200 GPUs"
      - name: Verify TORCH_CI_MAX_MEMORY
        run: |
          echo "=== TORCH_CI_MAX_MEMORY ==="
          EXPECTED=483183820800
          ACTUAL="${TORCH_CI_MAX_MEMORY:-}"
          echo "TORCH_CI_MAX_MEMORY=$ACTUAL (expected: $EXPECTED)"
          if [ -z "$ACTUAL" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY is not set"
            exit 1
          fi
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "FAIL: TORCH_CI_MAX_MEMORY mismatch"
            exit 1
          fi
          echo "PASS: TORCH_CI_MAX_MEMORY is correct"
  # END_B200

  # ── BuildKit Tests ────────────────────────────────────────────────────
  build-amd64:
    uses: ./.github/workflows/build-image.yaml
    with:
      arch: amd64
      runner_label: {{PREFIX}}l-x86iamx-8-32

  build-arm64:
    uses: ./.github/workflows/build-image.yaml
    with:
      arch: arm64
      runner_label: {{PREFIX}}l-x86iamx-8-32

  # ── Harbor Cache Test ─────────────────────────────────────────────────
  test-harbor:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify container is running
        run: |
          echo "PASS: Container started successfully"
          echo "This proves Harbor pull-through cache works for ghcr.io"
      - name: Verify containerd mirror config
        run: |
          echo "=== Containerd mirror config ==="
          if [ -d /etc/containerd/certs.d ]; then
            ls -la /etc/containerd/certs.d/ || true
            echo "PASS: Mirror config directory exists"
          else
            echo "INFO: /etc/containerd/certs.d not visible from container (expected)"
            echo "PASS: Container pulled successfully through Harbor"
          fi

  # BEGIN_CACHE_ENFORCER
  # ── Cache Enforcer Test ──────────────────────────────────────────────
  test-cache-enforcer:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify blocked registry domains
        run: |
          echo "=== Cache Enforcer: Registry Domain Blocking ==="
          BLOCKED_REGISTRIES="
            docker.io
            registry-1.docker.io
            auth.docker.io
            production.cloudflare.docker.com
            ghcr.io
            nvcr.io
            quay.io
            registry.k8s.io
          "
          FAIL=0
          for domain in $BLOCKED_REGISTRIES; do
            [ -z "$domain" ] && continue
            if curl --connect-timeout 5 --max-time 10 -s -o /dev/null "https://$domain/" 2>/dev/null; then
              echo "FAIL: $domain is reachable (should be blocked)"
              FAIL=1
            else
              echo "PASS: $domain is blocked"
            fi
          done
          if [ "$FAIL" -ne 0 ]; then
            echo ""
            echo "FAIL: One or more registry domains were reachable"
            exit 1
          fi
          echo ""
          echo "PASS: All registry domains blocked by cache-enforcer"
      - name: Verify blocked PyPI domains
        run: |
          echo "=== Cache Enforcer: PyPI Domain Blocking ==="
          BLOCKED_PYPI="
            pypi.org
            files.pythonhosted.org
          "
          FAIL=0
          for domain in $BLOCKED_PYPI; do
            [ -z "$domain" ] && continue
            if curl --connect-timeout 5 --max-time 10 -s -o /dev/null "https://$domain/" 2>/dev/null; then
              echo "FAIL: $domain is reachable (should be blocked)"
              FAIL=1
            else
              echo "PASS: $domain is blocked"
            fi
          done
          if [ "$FAIL" -ne 0 ]; then
            echo ""
            echo "FAIL: One or more PyPI domains were reachable"
            exit 1
          fi
          echo ""
          echo "PASS: All PyPI domains blocked by cache-enforcer"
      - name: Verify non-blocked domains work
        run: |
          echo "=== Cache Enforcer: Non-blocked Domain Validation ==="
          ALLOWED_DOMAINS="
            public.ecr.aws
            github.com
          "
          FAIL=0
          for domain in $ALLOWED_DOMAINS; do
            [ -z "$domain" ] && continue
            HTTP_CODE=$(curl --connect-timeout 10 --max-time 15 -s -o /dev/null -w "%{http_code}" "https://$domain/" 2>/dev/null || echo "000")
            if [ "$HTTP_CODE" = "000" ]; then
              echo "FAIL: $domain is unreachable (should NOT be blocked)"
              FAIL=1
            else
              echo "PASS: $domain is reachable (HTTP $HTTP_CODE)"
            fi
          done
          if [ "$FAIL" -ne 0 ]; then
            echo ""
            echo "FAIL: Non-blocked domains are unreachable — possible network issue"
            exit 1
          fi
          echo ""
          echo "PASS: Non-blocked domains are accessible"
  # END_CACHE_ENFORCER

  # ── PyPI Proxy Test ──────────────────────────────────────────────────
  test-pypi-proxy:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: python:3.12-slim
    steps:
      - name: Verify pypi-cache service health
        run: |
          echo "=== PyPI Cache: Service Health Check ==="
          SLUGS="{{PYPI_CACHE_SLUGS}}"
          FAIL=0
          for slug in $SLUGS; do
            URL="http://pypi-cache-${slug}.pypi-cache.svc.cluster.local:8080/simple/"
            HTTP_CODE=$(python3 -c "
          import urllib.request, sys
          try:
              r = urllib.request.urlopen('$URL', timeout=15)
              print(r.status)
          except Exception as e:
              print(f'000 ({e})', file=sys.stderr)
              print('000')
          ")
            if [ "$HTTP_CODE" = "200" ]; then
              echo "PASS: pypi-cache-${slug} responded HTTP $HTTP_CODE"
            else
              echo "FAIL: pypi-cache-${slug} returned HTTP $HTTP_CODE (expected 200)"
              FAIL=1
            fi
          done
          if [ "$FAIL" -ne 0 ]; then
            echo ""
            echo "FAIL: One or more pypi-cache services are unhealthy"
            exit 1
          fi
          echo ""
          echo "PASS: All pypi-cache services healthy"
      - name: Verify pip install via pypi-cache
        run: |
          echo "=== PyPI Cache: Install Verification ==="
          echo "PIP_INDEX_URL=${PIP_INDEX_URL:-<not set>}"
          echo "PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST:-<not set>}"
          echo ""
          echo "--- bare pip install (should use pod-level env vars) ---"
          pip install --no-cache-dir six
          echo "PASS: pip install via pypi-cache succeeded"
          pip uninstall -y six >/dev/null 2>&1
      - name: Verify URL rewriting (sub_filter)
        run: |
          echo "=== PyPI Cache: URL Rewriting Verification ==="
          SLUG=$(echo "{{PYPI_CACHE_SLUGS}}" | awk '{print $1}')
          URL="http://pypi-cache-${SLUG}.pypi-cache.svc.cluster.local:8080/simple/six/"
          FAILED=0

          for CONTENT_TYPE in "text/html" "application/vnd.pypi.simple.v1+json"; do
            echo ""
            echo "--- Testing with Accept: ${CONTENT_TYPE} ---"
            BODY=$(python3 -c "
          import urllib.request
          req = urllib.request.Request('$URL', headers={'Accept': '${CONTENT_TYPE}'})
          r = urllib.request.urlopen(req, timeout=15)
          print(r.read().decode())
          ")
            echo "Checking for unrewritten URLs..."
            DIRECT_COUNT=$(echo "$BODY" | grep -c 'files.pythonhosted.org' || true)
            if [ "$DIRECT_COUNT" -ne 0 ]; then
              echo "FAIL: Found $DIRECT_COUNT unrewritten files.pythonhosted.org URLs"
              echo "$BODY" | grep 'files.pythonhosted.org' | head -3
              FAILED=1
            else
              echo "PASS: No files.pythonhosted.org URLs in response"
            fi

            echo "Checking for rewritten /packages/ URLs..."
            PKG_COUNT=$(echo "$BODY" | grep -c '/packages/' || true)
            if [ "$PKG_COUNT" -eq 0 ]; then
              echo "FAIL: No /packages/ URLs found in response"
              FAILED=1
            else
              echo "PASS: Found $PKG_COUNT rewritten /packages/ URLs"
            fi
          done

          if [ "$FAILED" -ne 0 ]; then
            echo ""
            echo "FAIL: URL rewriting verification failed for one or more content types"
            exit 1
          fi
          echo ""
          echo "PASS: URL rewriting verified for both text/html and PEP 691 JSON"
