# Auto-generated by OSDC integration test orchestrator.
# Do not edit manually — regenerated on each test run.
name: "OSDC Integration Test"

on:
  pull_request:

concurrency:
  group: osdc-integration-test-{{CLUSTER_ID}}
  cancel-in-progress: true

jobs:
  # ── CPU Runner Tests ──────────────────────────────────────────────────
  test-cpu-x86-avx512:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify CPU architecture
        run: |
          echo "=== CPU Info ==="
          lscpu
          echo ""
          echo "=== Checking x86_64 ==="
          ARCH=$(uname -m)
          if [ "$ARCH" != "x86_64" ]; then
            echo "FAIL: Expected x86_64, got $ARCH"
            exit 1
          fi
          echo "PASS: Architecture is $ARCH"
      - name: Verify AVX-512 support
        run: |
          if grep -q avx512 /proc/cpuinfo; then
            echo "PASS: AVX-512 flags found"
          else
            echo "FAIL: AVX-512 flags not found in /proc/cpuinfo"
            exit 1
          fi
      - name: Verify resources
        run: |
          echo "=== Memory ==="
          free -h
          echo ""
          echo "=== Disk ==="
          df -h
      - name: Verify environment
        run: |
          echo "=== Environment ==="
          echo "CHECKOUT_GIT_CACHE_DIR=${CHECKOUT_GIT_CACHE_DIR:-NOT SET}"
          echo "GIT_CONFIG_SYSTEM=${GIT_CONFIG_SYSTEM:-NOT SET}"
          echo "ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER=${ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER:-NOT SET}"
          if [ -z "${CHECKOUT_GIT_CACHE_DIR:-}" ]; then
            echo "FAIL: CHECKOUT_GIT_CACHE_DIR not set"
            exit 1
          fi
          echo "PASS: Required env vars present"

  test-cpu-x86-amx:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify CPU architecture
        run: |
          echo "=== CPU Info ==="
          lscpu
          ARCH=$(uname -m)
          if [ "$ARCH" != "x86_64" ]; then
            echo "FAIL: Expected x86_64, got $ARCH"
            exit 1
          fi
          echo "PASS: Architecture is $ARCH"
      - name: Verify AMX support
        run: |
          if grep -q amx /proc/cpuinfo; then
            echo "PASS: AMX flags found"
          else
            echo "WARN: AMX flags not found (may not be exposed in container)"
          fi
      - name: Verify resources
        run: |
          echo "=== Memory ==="
          free -h
          echo ""
          echo "=== Disk ==="
          df -h

  test-cpu-arm64:
    runs-on: {{PREFIX}}l-arm64g3-16-62
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify CPU architecture
        run: |
          echo "=== CPU Info ==="
          lscpu
          ARCH=$(uname -m)
          if [ "$ARCH" != "aarch64" ]; then
            echo "FAIL: Expected aarch64, got $ARCH"
            exit 1
          fi
          echo "PASS: Architecture is $ARCH"
      - name: Verify resources
        run: |
          echo "=== Memory ==="
          free -h
          echo ""
          echo "=== Disk ==="
          df -h
      - name: Verify environment
        run: |
          echo "CHECKOUT_GIT_CACHE_DIR=${CHECKOUT_GIT_CACHE_DIR:-NOT SET}"
          if [ -z "${CHECKOUT_GIT_CACHE_DIR:-}" ]; then
            echo "FAIL: CHECKOUT_GIT_CACHE_DIR not set"
            exit 1
          fi
          echo "PASS: Required env vars present"

  # ── Git Cache Test ────────────────────────────────────────────────────
  test-git-cache:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify cache mount
        run: |
          echo "=== Git Cache ==="
          echo "CHECKOUT_GIT_CACHE_DIR=${CHECKOUT_GIT_CACHE_DIR:-NOT SET}"
          if [ ! -d "${CHECKOUT_GIT_CACHE_DIR:-/nonexistent}" ]; then
            echo "FAIL: Git cache directory not mounted"
            exit 1
          fi
          echo "PASS: Git cache directory exists at $CHECKOUT_GIT_CACHE_DIR"
          echo ""
          echo "=== Cache contents ==="
          ls -la "$CHECKOUT_GIT_CACHE_DIR/" || true
      - name: Verify pytorch cache
        run: |
          CACHE_DIR="$CHECKOUT_GIT_CACHE_DIR/pytorch"
          if [ ! -d "$CACHE_DIR/.git/objects" ]; then
            echo "FAIL: pytorch/.git/objects not found"
            echo "Cache dir contents:"
            ls -la "$CHECKOUT_GIT_CACHE_DIR/" 2>/dev/null || echo "(empty)"
            exit 1
          fi
          OBJ_COUNT=$(find "$CACHE_DIR/.git/objects" -type f 2>/dev/null | head -100 | wc -l)
          echo "PASS: pytorch/pytorch cache has objects (sampled $OBJ_COUNT files)"
      - name: Verify test-infra cache
        run: |
          CACHE_DIR="$CHECKOUT_GIT_CACHE_DIR/test-infra.git"
          if [ ! -d "$CACHE_DIR/objects" ]; then
            echo "FAIL: test-infra.git/objects not found"
            exit 1
          fi
          echo "PASS: pytorch/test-infra cache present"
      - name: Test fast checkout with cache
        uses: actions/checkout@v4
        with:
          repository: pytorch/pytorch
          ref: main
          path: pytorch-checkout
          fetch-depth: 1
      - name: Verify checkout
        run: |
          if [ ! -f "pytorch-checkout/setup.py" ]; then
            echo "FAIL: Checkout doesn't look like pytorch/pytorch"
            exit 1
          fi
          echo "PASS: pytorch/pytorch checkout verified"

  # ── GPU Runner Tests ──────────────────────────────────────────────────
  test-gpu-t4:
    runs-on: {{PREFIX}}l-x86iavx512-29-115-t4
    container:
      image: nvidia/cuda:12.6.3-base-ubuntu22.04
    steps:
      - name: Verify GPU
        run: |
          echo "=== nvidia-smi ==="
          nvidia-smi
          echo ""
          GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
          if [ "$GPU_COUNT" -lt 1 ]; then
            echo "FAIL: Expected at least 1 GPU, found $GPU_COUNT"
            exit 1
          fi
          echo "PASS: Found $GPU_COUNT GPU(s)"
      - name: Verify GPU model
        run: |
          GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
          echo "GPU: $GPU_NAME"
          if echo "$GPU_NAME" | grep -qi "t4"; then
            echo "PASS: GPU is T4"
          else
            echo "WARN: Expected T4, got $GPU_NAME"
          fi
      - name: Verify CUDA
        run: |
          echo "=== CUDA Version ==="
          nvcc --version 2>/dev/null || echo "nvcc not in PATH (base image only)"
          nvidia-smi --query-gpu=driver_version --format=csv,noheader
          echo "PASS: GPU driver responsive"

  test-gpu-t4-multi:
    runs-on: {{PREFIX}}l-x86iavx512-45-172-t4-4
    container:
      image: nvidia/cuda:12.6.3-base-ubuntu22.04
    steps:
      - name: Verify multi-GPU
        run: |
          echo "=== nvidia-smi ==="
          nvidia-smi
          echo ""
          GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
          if [ "$GPU_COUNT" -ne 4 ]; then
            echo "FAIL: Expected 4 GPUs, found $GPU_COUNT"
            exit 1
          fi
          echo "PASS: Found $GPU_COUNT GPUs"
      - name: Verify GPU topology
        run: |
          echo "=== GPU Topology ==="
          nvidia-smi topo -m

  # BEGIN_B200
  test-gpu-b200-1:
    runs-on: a.linux.b200
    container:
      image: nvidia/cuda:12.6.3-base-ubuntu22.04
    steps:
      - name: Verify B200 GPU
        run: |
          echo "=== nvidia-smi ==="
          nvidia-smi
          echo ""
          GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
          if [ "$GPU_COUNT" -lt 1 ]; then
            echo "FAIL: Expected at least 1 GPU, found $GPU_COUNT"
            exit 1
          fi
          GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
          echo "GPU: $GPU_NAME"
          echo "PASS: B200 GPU accessible"

  test-gpu-b200-2:
    runs-on: a.linux.b200.2
    container:
      image: nvidia/cuda:12.6.3-base-ubuntu22.04
    steps:
      - name: Verify B200 multi-GPU
        run: |
          echo "=== nvidia-smi ==="
          nvidia-smi
          echo ""
          GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
          if [ "$GPU_COUNT" -ne 2 ]; then
            echo "FAIL: Expected 2 GPUs, found $GPU_COUNT"
            exit 1
          fi
          echo "PASS: Found $GPU_COUNT B200 GPUs"

  test-gpu-b200-8:
    runs-on: a.linux.b200.8
    container:
      image: nvidia/cuda:12.6.3-base-ubuntu22.04
    steps:
      - name: Verify B200 full-node
        run: |
          echo "=== nvidia-smi ==="
          nvidia-smi
          echo ""
          GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
          if [ "$GPU_COUNT" -ne 8 ]; then
            echo "FAIL: Expected 8 GPUs, found $GPU_COUNT"
            exit 1
          fi
          echo "PASS: Found $GPU_COUNT B200 GPUs"
      - name: Verify GPU topology
        run: |
          echo "=== GPU Topology ==="
          nvidia-smi topo -m
  # END_B200

  # ── BuildKit Tests ────────────────────────────────────────────────────
  build-amd64:
    uses: ./.github/workflows/build-image.yaml
    with:
      arch: amd64
      runner_label: {{PREFIX}}l-x86iamx-8-32

  build-arm64:
    uses: ./.github/workflows/build-image.yaml
    with:
      arch: arm64
      runner_label: {{PREFIX}}l-x86iamx-8-32

  # ── Harbor Cache Test ─────────────────────────────────────────────────
  test-harbor:
    runs-on: {{PREFIX}}l-x86iamx-8-32
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Verify container is running
        run: |
          echo "PASS: Container started successfully"
          echo "This proves Harbor pull-through cache works for ghcr.io"
      - name: Verify containerd mirror config
        run: |
          echo "=== Containerd mirror config ==="
          if [ -d /etc/containerd/certs.d ]; then
            ls -la /etc/containerd/certs.d/ || true
            echo "PASS: Mirror config directory exists"
          else
            echo "INFO: /etc/containerd/certs.d not visible from container (expected)"
            echo "PASS: Container pulled successfully through Harbor"
          fi
