alertmanager:
  enabled: false

server:
  persistentVolume:
    storageClass: "gp2"
  service:
    type: NodePort
  retention: "365d"
  extraFlags:
    - "web.enable-remote-write-receiver"

alertmanagerFiles:
  alertmanager.yml: ""

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: true
  service:
    type: NodePort

