name: ALI On PR

on:
  pull_request:
    paths:
      - '.github/workflows/ali-*'
      - 'ali/**'
      - 'modules/**'
      - 'scripts/**'
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  tflint-plan:
    name: ALI tflint + terraform plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
        terraform_wrapper: false

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install virtualenv
      run: pip install virtualenv

    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1
      with:
        arch: amd64

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.PY_FOUNDATION_AWS_ACC_ID }}:role/${{ secrets.PY_FOUNDATION_AWS_DEPLOY_ROLE }}
        aws-region: us-east-1

    - name: "Run TFLint runners"
      shell: bash
      working-directory: ali
      run: make tflint

    - name: Make plan
      shell: bash
      working-directory: ali
      run: make plan
      env:
        TERRAFORM_EXTRAS: -lock-timeout=15m
