name: Terraform Apply / Runners / Production - ARC

on:
  workflow_dispatch:

concurrency:
  group: "terraform-make-apply"
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install Terraform
      uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1.0.5
      with:
        terraform_version: 1.5.7
        terraform_wrapper: false

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.PY_FOUNDATION_AWS_ACC_ID }}:role/${{ secrets.PY_FOUNDATION_AWS_DEPLOY_ROLE }}
        aws-region: us-east-1

    - name: Terraform Apply
      working-directory: arc/aws/391835788720/us-east-1
      shell: bash
      run: make apply
      env:
        AWS_DEFAULT_REGION: us-east-1
        GITHUB_TOKEN: ${{ secrets.LIST_PYTORCH_RUNNERS_GITHUB_TOKEN }}
        TERRAFORM_EXTRAS: -auto-approve -lock-timeout=15m
        TF_VAR_git_revision: ${{ github.ref_name }}
