name: Runners Open Release PR

on:
  workflow_dispatch:
    inputs:
      fast_release_firefight:
        description: 'Skip terraform plan validation and old instance removal (cattle spa) [Use for firefighting]'
        required: true
        default: 'false'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  open_releae_pr:
    name: Open Release PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Install virtualenv
      run: pip install virtualenv

    - name: Open PR
      shell: bash
      run: make open-rel-pr
      env:
        GHA_PRIVATE_KEY_DEPLOY : ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
        GITHUB_APP_ID: ${{ secrets.RELEASE_APP_ID }}
        GITHUB_APP_INSTALLATION_ID: ${{ secrets.RELEASE_APP_INSTALLATION_ID }}
        GITHUB_REPOSITORY: ${{ github.repository }}
