name: Hack to build image because Mac doesn't support Docker properly

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-canary:
    name: Deploy to Canary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    # - name: Install Terraform
    #   uses: hashicorp/setup-terraform@v2
    #   with:
    #     terraform_version: 1.5.7
    #     terraform_wrapper: false

    # - name: Install virtualenv
    #   run: pip install virtualenv

    # - name: Install AWS CLI
    #   uses: unfor19/install-aws-cli-action@v1
    #   with:
    #     arch: amd64

    # - name: Install Kubectl
    #   uses: azure/setup-kubectl@v1
    #   with:
    #     version: latest

    # - name: Install Helm
    #   uses: azure/setup-helm@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     version: latest

    # - name: configure aws credentials
    #   uses: aws-actions/configure-aws-credentials@v1.7.0
    #   with:
    #     role-to-assume:  arn:aws:iam::${{ secrets.PY_FOUNDATION_AWS_ACC_ID }}:role/${{ secrets.PY_FOUNDATION_AWS_DEPLOY_ROLE }}
    #     aws-region: us-east-1

    # - name: Build Runner Images
    #   run: make build-runner-images
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     PUSH_PACKAGE_DOCKER_GITHUB_TOKEN: ${{ secrets.PUSH_PACKAGE_DOCKER_GITHUB_TOKEN }}

