apiVersion: v1
kind: Service
metadata:
  name: git-cache-central-headless
  namespace: kube-system
  labels:
    app: git-cache-central
    app.kubernetes.io/name: git-cache-central
    app.kubernetes.io/component: git-cache
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: rsync
      port: 873
      targetPort: 873
    - name: metrics
      port: 9101
      targetPort: 9101
  selector:
    app: git-cache-central
